version: '2'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - pgsql-data:/var/lib/postgresql/data
volumes:
  pgsql-data:
